# SPDX-FileCopyrightText: 2023 Antoine Belvire
# SPDX-License-Identifier: GPL-3.0-or-later

variables:
  GIT_SUBMODULE_STRATEGY: normal
  # Include only Crossword Composer submodule, LibreOffice dictionaries are not required for build
  GIT_SUBMODULE_PATHS: croiseur-solver/croiseur-solver-paulgb/crossword-composer

stages:
  - build

build linux:
  # Use a tailored image derived from a minimal openSUSE Tumbleweed image.
  # See https://build.opensuse.org/package/show/home:1Antoine1:croiseur:head/croiseur-build-platform.
  image: registry.opensuse.org/home/1antoine1/croiseur/head/tumbleweed_containers/opensuse/croiseur-build-platform:15.1
  stage: build
  script:
    - reuse lint
    - gradle --parallel assemble -x distZip
    - gradle --parallel check
    - gradle --parallel distZip
    - gradle --parallel publish -Pcroiseur.maven.token.name="Job-Token" -Pcroiseur.maven.toke.value="${CI_JOB_TOKEN}"
  artifacts:
    paths:
      - "croiseur-cli/build/distributions/croiseur-cli*.zip"
      - "croiseur-gui/croiseur-gui/build/distributions/croiseur-gui*.zip"