[versions]
cargo = "1.1.0"
java = "17.0.2"
javafx = "0.0.13"
junit5 = "5.9.1"
native = "0.9.10"
picocli = "4.7.0"

[libraries]
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
native = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "native" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
picocli-framework = { module = "info.picocli:picocli", version.ref = "picocli" }

[plugins]
cargo = { id = "io.github.arc-blroth.cargo-wrapper", version.ref = "cargo"}
native = { id = "org.graalvm.buildtools.native", version.ref = "native" }
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx" }