# SPDX-FileCopyrightText: 2023 Antoine Belvire
# SPDX-License-Identifier: GPL-3.0-or-later

[versions]
cargo = "1.1.0"
java = "17.0.2"
javafx = "0.0.13"
junit5 = "5.9.1"
native = "0.9.10"
picocli = "4.7.1"

[libraries]
# Test libraries, used by all modules
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
# Picocli is a framework for building command-line applications; only used by cli module
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
picocli-framework = { module = "info.picocli:picocli", version.ref = "picocli" }

[plugins]
# Plugin to help embedding rust code, only used by one solver module for now
cargo = { id = "io.github.arc-blroth.cargo-wrapper", version.ref = "cargo"}
# For creating native executable using GraalVM, only used by cli module for now
native = { id = "org.graalvm.buildtools.native", version.ref = "native" }
# Plugin to pull JavaFx; only used by gui module
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx" }
