# SPDX-FileCopyrightText: 2023 Antoine Belvire
# SPDX-License-Identifier: GPL-3.0-or-later

[versions]
cargo-plugin = "1.1.0"
cucumber = "7.12.0"
java = "17.0.7"
javafx-plugin = "0.0.13"
junit5 = "5.9.3"
junit5-platform = "1.9.3"
mockito = "5.3.1"
native-plugin = "0.9.21"
picocli = "4.7.3"

[libraries]
# BDD library, for acceptance tests
cucumber = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit5-engine = { module = "io.cucumber:cucumber-junit-platform-engine", version.ref = "cucumber" }
cucumber-picocontainer = { module = "io.cucumber:cucumber-picocontainer", version.ref = "cucumber" }
# Test libraries, used by all modules by convention
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit5-platform" }
# Additional test library for mock objects
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
# A plugin for creating native executable using GraalVM, only used by cli module for now. It
# should be in the plugin section but somehow gradle doesn't recognize it in buildSrc
native = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "native-plugin" }
# Picocli is a framework for building command-line applications; only used by cli module
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
picocli-framework = { module = "info.picocli:picocli", version.ref = "picocli" }

[plugins]
# Plugin to help embedding rust code, only used by native solvers
cargo = { id = "io.github.arc-blroth.cargo-wrapper", version.ref = "cargo-plugin" }
# Plugin to pull JavaFx; only used by gui module
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx-plugin" }
