'SPDX-FileCopyrightText: 2023 Antoine Belvire
'SPDX-License-Identifier: GPL-3.0-or-later

@startdot
digraph "clues" {
  // All nodes are components
  node [shape=component];

  // External dependencies need to be distinguished from the rest
  "com.azure.ai.openai" [style=filled fillcolor=lightgray]
  "com.azure.http.netty" [style=filled fillcolor=lightgray]
  "com.azure.core" [style=filled fillcolor=lightgray]
  "com.azure.json" [style=filled fillcolor=lightgray]
  "io.netty.*" [style=filled fillcolor=lightgray]
  "org.reactivestreams" [style=filled fillcolor=lightgray]
  "org.slf4j" [style=filled fillcolor=lightgray]
  "reactor.core" [style=filled fillcolor=lightgray]
  "com.fasterxml.jackson.datatype.jsr310" [style=filled fillcolor=lightgray]
  "com.fasterxml.jackson.databind" [style=filled fillcolor=lightgray]
  "com.fasterxml.jackson.annotation" [style=filled fillcolor=lightgray]
  "com.fasterxml.jackson.core" [style=filled fillcolor=lightgray]
  "java.base" [style=filled fillcolor=lightgray]
  "java.xml" [style=filled fillcolor=lightgray]

  "croiseur.clue.openai.plugin" -> "croiseur.spi.clue" [label="provides"]
  "croiseur.spi.clue" -> "java.base"

  "org.slf4j"                                        -> "java.base";
  "com.azure.json"                                   -> "java.base";
  "com.fasterxml.jackson.databind"                   -> "com.fasterxml.jackson.annotation";
  "com.fasterxml.jackson.databind"                   -> "com.fasterxml.jackson.core";
  "com.fasterxml.jackson.databind"                   -> "java.xml";
  "java.xml"                                         -> "java.base"
  "org.reactivestreams"                              -> "java.base";
  "reactor.core"                                     -> "org.reactivestreams";
  "reactor.core"                                     -> "org.slf4j";
  "croiseur.clue.openai.plugin"                      -> "com.azure.ai.openai";
  "com.fasterxml.jackson.annotation"                 -> "java.base";
  "com.azure.core"                                   -> "com.azure.json";
  "com.azure.core"                                   -> "com.fasterxml.jackson.datatype.jsr310";
  "com.azure.core"                                   -> "reactor.core";
  "com.fasterxml.jackson.core"                       -> "java.base";
  "com.fasterxml.jackson.datatype.jsr310"            -> "com.fasterxml.jackson.databind";
  "com.azure.ai.openai"                              -> "com.azure.core";

  // runtime dependencies, let's mention them
  "com.azure.http.netty" -> "com.azure.core"
  "com.azure.http.netty" -> "io.netty.*"
}
@enddot
