@startdot
digraph "solvers" {
  // All nodes are components
  node [shape=component];

  // External dependencies need to be distinguished from the rest
  "java.base" [style=filled fillcolor=lightgray];

  "croiseur.puzzle.codec.xd.plugin" -> "croiseur.spi.puzzle.codec" [label=provides];
  "croiseur.puzzle.codec.xd.plugin" -> "croiseur.puzzle.codec.xd";
  "croiseur.spi.puzzle.codec" -> "croiseur.common";
  "croiseur.common"   -> "java.base";
  "croiseur.puzzle.codec.xd" -> "java.base"
}
@enddot